project_id = "rvmvoogyrafiogxdbisx"

[functions.chat-travel]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.google-places]
verify_jwt = false

[functions.foursquare-places]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.flight-prices]
verify_jwt = false

[functions.fetch-travel-images]
verify_jwt = false

[functions.osm-tile-proxy]
verify_jwt = false
